// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomoOYVLGYHsz9Ad633Tqd6eNE8uvrjlg',
    appId: '1:443364126859:web:3c2a527b64aac4d469a48e',
    messagingSenderId: '443364126859',
    projectId: 'produtos-8d265',
    authDomain: 'produtos-8d265.firebaseapp.com',
    databaseURL: 'https://produtos-8d265-default-rtdb.firebaseio.com',
    storageBucket: 'produtos-8d265.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLE0P4r9EN9mLrbVWjkZ8UC5mhTLqkCAY',
    appId: '1:443364126859:android:e8b8328dafa7a5e069a48e',
    messagingSenderId: '443364126859',
    projectId: 'produtos-8d265',
    databaseURL: 'https://produtos-8d265-default-rtdb.firebaseio.com',
    storageBucket: 'produtos-8d265.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZwagqHtu5CB7OCcG8Gvb6IgCFeUXuluU',
    appId: '1:443364126859:ios:8c894904ad011d3f69a48e',
    messagingSenderId: '443364126859',
    projectId: 'produtos-8d265',
    databaseURL: 'https://produtos-8d265-default-rtdb.firebaseio.com',
    storageBucket: 'produtos-8d265.appspot.com',
    iosClientId: '443364126859-q03ub44pkb5kil1pshd5k5lal542r353.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchallenge',
  );
}
